### ISSUE TITLE
Syntax error?

### ISSUE THREAD

**Issue by CaledoniaProject** [m8r0wn/nullinux#3]
The script contains an extra comma

```
%> python nullinux.py
  File "nullinux.py", line 89
    print "\n   ",
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "\n   ", end=" ")?
```

**Comment by m8sec** [comment]
Hi @CaledoniaProject,

First off, thank you for using the tool Im glad your finding it helpful! Nullinux v5 was rewritten in python3 and released in a separate branch. To download that version please use: 
_git clone -b python3 https://github.com/m8r0wn/nullinux_. 

Not wanting to make drastic changes so quickly, the master branch remains Python2.7. I have just checked that line 89 does not cause an issue. I hope to make the full switch over to Python3 in the near future. 

Thanks,
m8r0wn

**Comment by CaledoniaProject** [comment]
Thanks :-)
