### ISSUE TITLE
Coding is/was a little off for me 

### ISSUE THREAD

**Issue by momoisacat** [m8r0wn/nullinux#4]
When i would run with a range of ip addresses the  code would completely ignore the range and go from the third octet and count from there.
I changed line 271 to for x in range(int(c[3]), int(b)+1): from for x in range(int(c[2]), int(b)+1):

Thank you,
Have a great day
-Momo

**Comment by m8sec** [comment]
Good catch, all branches have been updated!

Thanks,
m8r0wn
